# Generated by Django 6.0.2 on 2026-03-04 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('input_word', models.TextField(max_length=1000, verbose_name='意味を知りたい単語')),
                ('return_mean', models.CharField(max_length=100, verbose_name='その単語の意味')),
                ('thoughts', models.TextField(blank=True, max_length=1000, verbose_name='このドキュメントを読んだ感想(空欄可)')),
                ('page_date', models.DateField(verbose_name='日付')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
