# Generated by Django 6.0.2 on 2026-03-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='wisme/picture/', verbose_name='写真'),
        ),
    ]
