# Generated by Django 6.0.2 on 2026-03-13 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0002_page_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='return_mean',
        ),
    ]
