# Generated by Django 6.0.2 on 2026-03-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0003_remove_page_return_mean'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='return_mean',
            field=models.CharField(max_length=100, null=True, verbose_name='その単語の意味'),
        ),
    ]
