# Generated by Django 6.0.2 on 2026-03-13 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisme', '0004_page_return_mean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='input_word',
        ),
        migrations.RemoveField(
            model_name='page',
            name='return_mean',
        ),
        migrations.CreateModel(
            name='SearchedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, verbose_name='意味を知りたい単語')),
                ('meaning', models.TextField(verbose_name='意味')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='検索日時')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='words', to='wisme.page', verbose_name='関連メモ')),
            ],
        ),
    ]
